/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShortsRouteImport } from './routes/shorts'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as ApiVideoRouteImport } from './routes/api/video'
import { Route as InfoSlugRouteImport } from './routes/info.$slug'
import { Route as RoomsIndexRouteImport } from './routes/rooms.index'
import { Route as RoomsIdRouteImport } from './routes/rooms.$id'
import { Route as StudioShopRouteImport } from './routes/studio.shop'
import { Route as StudioUploadRouteImport } from './routes/studio.upload'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiPublicOgRouteImport } from './routes/api/public/og'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortsRoute = ShortsRouteImport.update({
  id: '/shorts',
  path: '/shorts',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVideoRoute = ApiVideoRouteImport.update({
  id: '/api/video',
  path: '/api/video',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoSlugRoute = InfoSlugRouteImport.update({
  id: '/info/$slug',
  path: '/info/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIdRoute = RoomsIdRouteImport.update({
  id: '/rooms/$id',
  path: '/rooms/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioShopRoute = StudioShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => StudioRoute,
} as any)
const StudioUploadRoute = StudioUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => StudioRoute,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOgRoute = ApiPublicOgRouteImport.update({
  id: '/api/public/og',
  path: '/api/public/og',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/shorts': typeof ShortsRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/video': typeof ApiVideoRoute
  '/info/$slug': typeof InfoSlugRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/studio/shop': typeof StudioShopRoute
  '/studio/upload': typeof StudioUploadRoute
  '/watch/$id': typeof WatchIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/public/og': typeof ApiPublicOgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/shorts': typeof ShortsRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/video': typeof ApiVideoRoute
  '/info/$slug': typeof InfoSlugRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/studio/shop': typeof StudioShopRoute
  '/studio/upload': typeof StudioUploadRoute
  '/watch/$id': typeof WatchIdRoute
  '/rooms': typeof RoomsIndexRoute
  '/api/public/og': typeof ApiPublicOgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/auth': typeof AuthRoute
  '/feed': typeof FeedRoute
  '/notifications': typeof NotificationsRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/shorts': typeof ShortsRoute
  '/studio': typeof StudioRouteWithChildren
  '/api/video': typeof ApiVideoRoute
  '/info/$slug': typeof InfoSlugRoute
  '/rooms/$id': typeof RoomsIdRoute
  '/studio/shop': typeof StudioShopRoute
  '/studio/upload': typeof StudioUploadRoute
  '/watch/$id': typeof WatchIdRoute
  '/rooms/': typeof RoomsIndexRoute
  '/api/public/og': typeof ApiPublicOgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/auth'
    | '/feed'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/shop'
    | '/shorts'
    | '/studio'
    | '/api/video'
    | '/info/$slug'
    | '/rooms/$id'
    | '/studio/shop'
    | '/studio/upload'
    | '/watch/$id'
    | '/rooms/'
    | '/api/public/og'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/auth'
    | '/feed'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/shop'
    | '/shorts'
    | '/studio'
    | '/api/video'
    | '/info/$slug'
    | '/rooms/$id'
    | '/studio/shop'
    | '/studio/upload'
    | '/watch/$id'
    | '/rooms'
    | '/api/public/og'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/auth'
    | '/feed'
    | '/notifications'
    | '/search'
    | '/settings'
    | '/shop'
    | '/shorts'
    | '/studio'
    | '/api/video'
    | '/info/$slug'
    | '/rooms/$id'
    | '/studio/shop'
    | '/studio/upload'
    | '/watch/$id'
    | '/rooms/'
    | '/api/public/og'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AuthRoute: typeof AuthRoute
  FeedRoute: typeof FeedRoute
  NotificationsRoute: typeof NotificationsRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  ShortsRoute: typeof ShortsRoute
  StudioRoute: typeof StudioRouteWithChildren
  ApiVideoRoute: typeof ApiVideoRoute
  InfoSlugRoute: typeof InfoSlugRoute
  RoomsIdRoute: typeof RoomsIdRoute
  WatchIdRoute: typeof WatchIdRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  ApiPublicOgRoute: typeof ApiPublicOgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shorts': {
      id: '/shorts'
      path: '/shorts'
      fullPath: '/shorts'
      preLoaderRoute: typeof ShortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/video': {
      id: '/api/video'
      path: '/api/video'
      fullPath: '/api/video'
      preLoaderRoute: typeof ApiVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/$slug': {
      id: '/info/$slug'
      path: '/info/$slug'
      fullPath: '/info/$slug'
      preLoaderRoute: typeof InfoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$id': {
      id: '/rooms/$id'
      path: '/rooms/$id'
      fullPath: '/rooms/$id'
      preLoaderRoute: typeof RoomsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/shop': {
      id: '/studio/shop'
      path: '/shop'
      fullPath: '/studio/shop'
      preLoaderRoute: typeof StudioShopRouteImport
      parentRoute: typeof StudioRoute
    }
    '/studio/upload': {
      id: '/studio/upload'
      path: '/upload'
      fullPath: '/studio/upload'
      preLoaderRoute: typeof StudioUploadRouteImport
      parentRoute: typeof StudioRoute
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/og': {
      id: '/api/public/og'
      path: '/api/public/og'
      fullPath: '/api/public/og'
      preLoaderRoute: typeof ApiPublicOgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioShopRoute: typeof StudioShopRoute
  StudioUploadRoute: typeof StudioUploadRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioShopRoute: StudioShopRoute,
  StudioUploadRoute: StudioUploadRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AuthRoute: AuthRoute,
  FeedRoute: FeedRoute,
  NotificationsRoute: NotificationsRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  ShortsRoute: ShortsRoute,
  StudioRoute: StudioRouteWithChildren,
  ApiVideoRoute: ApiVideoRoute,
  InfoSlugRoute: InfoSlugRoute,
  RoomsIdRoute: RoomsIdRoute,
  WatchIdRoute: WatchIdRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  ApiPublicOgRoute: ApiPublicOgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
